apiVersion: 1
contactPoints:
  - orgId: 1
    name: Email Notification
    receivers:
      - uid: email1
        type: email
        settings:
          addresses: ${EMAIL_ADDRESSES}
          singleEmail: false
